safe:      true
permalink: pretty
highlighter: pygments
markdown:  redcarpet
exclude:   [ README.md, Gemfile, vendor ]

site:
    title:  William DURAND
    author: William Durand
    email:  will@drnd.me
    url:    http://williamdurand.fr

my_linkedin: http://linkedin.com/in/williamdurand
my_github:   http://www.github.com/willdurand
my_twitter:  http://www.twitter.com/couac
