safe:       true
permalink:  pretty
pygments:   true
markdown:   redcarpet
redcarpet:
    extensions: [ "tables", "no_intra_emphasis" ]

site:
    title:  William DURAND
    author: William Durand
    email:  william.durand1@gmail.com
    url:    http://www.williamdurand.fr

my_linkedin: http://linkedin.com/in/williamdurand
my_github:   http://www.github.com/willdurand
my_twitter:  http://www.twitter.com/couac
